INFRA_HFILES = common.h \
               utility.h \
               compiler.h \
               error.h \
               token.h \
               lexer.h \
               parser.h \
               symbol.h \

INFRA_CFILES = \

INFRA_CPPFILES = common.cpp \
                 utility.cpp \
                 compiler.cpp \
                 error.cpp \
                 token.cpp \
                 lexer.cpp \
                 parser.cpp \
                 symbol.cpp \
